const List<Country> countries = [
  Country(
    id: 3,
    name: 'Afghanistan',
    flag: '🇦🇫',
    code: 'AF',
    dialCode: '93',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 15,
    name: 'Åland Islands',
    flag: '🇦🇽',
    code: 'AX',
    dialCode: '358',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 6,
    name: 'Albania',
    flag: '🇦🇱',
    code: 'AL',
    dialCode: '355',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 62,
    name: 'Algeria',
    flag: '🇩🇿',
    code: 'DZ',
    dialCode: '213',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 11,
    name: 'American Samoa',
    flag: '🇦🇸',
    code: 'AS',
    dialCode: '1684',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 1,
    name: 'Andorra',
    flag: '🇦🇩',
    code: 'AD',
    dialCode: '376',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 8,
    name: 'Angola',
    flag: '🇦🇴',
    code: 'AO',
    dialCode: '244',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 5,
    name: 'Anguilla',
    flag: '🇦🇮',
    code: 'AI',
    dialCode: '1264',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 9,
    name: 'Antarctica',
    flag: '🇦🇶',
    code: 'AQ',
    dialCode: '672',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 4,
    name: 'Antigua and Barbuda',
    flag: '🇦🇬',
    code: 'AG',
    dialCode: '1268',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 10,
    name: 'Argentina',
    flag: '🇦🇷',
    code: 'AR',
    dialCode: '54',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 7,
    name: 'Armenia',
    flag: '🇦🇲',
    code: 'AM',
    dialCode: '374',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 14,
    name: 'Aruba',
    flag: '🇦🇼',
    code: 'AW',
    dialCode: '297',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 13,
    name: 'Australia',
    flag: '🇦🇺',
    code: 'AU',
    dialCode: '61',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 12,
    name: 'Austria',
    flag: '🇦🇹',
    code: 'AT',
    dialCode: '43',
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    id: 16,
    name: 'Azerbaijan',
    flag: '🇦🇿',
    code: 'AZ',
    dialCode: '994',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 32,
    name: 'Bahamas',
    flag: '🇧🇸',
    code: 'BS',
    dialCode: '1242',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 23,
    name: 'Bahrain',
    flag: '🇧🇭',
    code: 'BH',
    dialCode: '973',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 19,
    name: 'Bangladesh',
    flag: '🇧🇩',
    code: 'BD',
    dialCode: '880',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 18,
    name: 'Barbados',
    flag: '🇧🇧',
    code: 'BB',
    dialCode: '1246',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 36,
    name: 'Belarus',
    flag: '🇧🇾',
    code: 'BY',
    dialCode: '375',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 20,
    name: 'Belgium',
    flag: '🇧🇪',
    code: 'BE',
    dialCode: '32',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 37,
    name: 'Belize',
    flag: '🇧🇿',
    code: 'BZ',
    dialCode: '501',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 25,
    name: 'Benin',
    flag: '🇧🇯',
    code: 'BJ',
    dialCode: '229',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 27,
    name: 'Bermuda',
    flag: '🇧🇲',
    code: 'BM',
    dialCode: '1441',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 33,
    name: 'Bhutan',
    flag: '🇧🇹',
    code: 'BT',
    dialCode: '975',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 29,
    name: 'Bolivia, Plurinational State of bolivia',
    flag: '🇧🇴',
    code: 'BO',
    dialCode: '591',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 17,
    name: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    code: 'BA',
    dialCode: '387',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 35,
    name: 'Botswana',
    flag: '🇧🇼',
    code: 'BW',
    dialCode: '267',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 34,
    name: 'Bouvet Island',
    flag: '🇧🇻',
    code: 'BV',
    dialCode: '47',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 31,
    name: 'Brazil',
    flag: '🇧🇷',
    code: 'BR',
    dialCode: '55',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 106,
    name: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    code: 'IO',
    dialCode: '246',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 28,
    name: 'Brunei Darussalam',
    flag: '🇧🇳',
    code: 'BN',
    dialCode: '673',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 22,
    name: 'Bulgaria',
    flag: '🇧🇬',
    code: 'BG',
    dialCode: '359',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 21,
    name: 'Burkina Faso',
    flag: '🇧🇫',
    code: 'BF',
    dialCode: '226',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 24,
    name: 'Burundi',
    flag: '🇧🇮',
    code: 'BI',
    dialCode: '257',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 117,
    name: 'Cambodia',
    flag: '🇰🇭',
    code: 'KH',
    dialCode: '855',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 47,
    name: 'Cameroon',
    flag: '🇨🇲',
    code: 'CM',
    dialCode: '237',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 38,
    name: 'Canada',
    flag: '🇨🇦',
    code: 'CA',
    dialCode: '1',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 52,
    name: 'Cape Verde',
    flag: '🇨🇻',
    code: 'CV',
    dialCode: '238',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 124,
    name: 'Cayman Islands',
    flag: '🇰🇾',
    code: 'KY',
    dialCode: '345',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 41,
    name: 'Central African Republic',
    flag: '🇨🇫',
    code: 'CF',
    dialCode: '236',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 215,
    name: 'Chad',
    flag: '🇹🇩',
    code: 'TD',
    dialCode: '235',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 46,
    name: 'Chile',
    flag: '🇨🇱',
    code: 'CL',
    dialCode: '56',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 48,
    name: 'China',
    flag: '🇨🇳',
    code: 'CN',
    dialCode: '86',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 54,
    name: 'Christmas Island',
    flag: '🇨🇽',
    code: 'CX',
    dialCode: '61',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 39,
    name: 'Cocos (Keeling) Islands',
    flag: '🇨🇨',
    code: 'CC',
    dialCode: '61',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 49,
    name: 'Colombia',
    flag: '🇨🇴',
    code: 'CO',
    dialCode: '57',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 119,
    name: 'Comoros',
    flag: '🇰🇲',
    code: 'KM',
    dialCode: '269',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 42,
    name: 'Congo',
    flag: '🇨🇬',
    code: 'CG',
    dialCode: '242',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 40,
    name: 'Congo, The Democratic Republic of the Congo',
    flag: '🇨🇩',
    code: 'CD',
    dialCode: '243',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 45,
    name: 'Cook Islands',
    flag: '🇨🇰',
    code: 'CK',
    dialCode: '682',
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    id: 50,
    name: 'Costa Rica',
    flag: '🇨🇷',
    code: 'CR',
    dialCode: '506',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 44,
    name: "Côte d'Ivoire",
    flag: '🇨🇮',
    code: 'CI',
    dialCode: '225',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 98,
    name: 'Croatia',
    flag: '🇭🇷',
    code: 'HR',
    dialCode: '385',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 51,
    name: 'Cuba',
    flag: '🇨🇺',
    code: 'CU',
    dialCode: '53',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 55,
    name: 'Cyprus',
    flag: '🇨🇾',
    code: 'CY',
    dialCode: '357',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 56,
    name: 'Czech Republic',
    flag: '🇨🇿',
    code: 'CZ',
    dialCode: '420',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 59,
    name: 'Denmark',
    flag: '🇩🇰',
    code: 'DK',
    dialCode: '45',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 58,
    name: 'Djibouti',
    flag: '🇩🇯',
    code: 'DJ',
    dialCode: '253',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 60,
    name: 'Dominica',
    flag: '🇩🇲',
    code: 'DM',
    dialCode: '1767',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 61,
    name: 'Dominican Republic',
    flag: '🇩🇴',
    code: 'DO',
    dialCode: '1849',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 63,
    name: 'Ecuador',
    flag: '🇪🇨',
    code: 'EC',
    dialCode: '593',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 65,
    name: 'Egypt',
    flag: '🇪🇬',
    code: 'EG',
    dialCode: '20',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 210,
    name: 'El Salvador',
    flag: '🇸🇻',
    code: 'SV',
    dialCode: '503',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 88,
    name: 'Equatorial Guinea',
    flag: '🇬🇶',
    code: 'GQ',
    dialCode: '240',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 67,
    name: 'Eritrea',
    flag: '🇪🇷',
    code: 'ER',
    dialCode: '291',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 64,
    name: 'Estonia',
    flag: '🇪🇪',
    code: 'EE',
    dialCode: '372',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 69,
    name: 'Ethiopia',
    flag: '🇪🇹',
    code: 'ET',
    dialCode: '251',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 72,
    name: 'Falkland Islands (Malvinas)',
    flag: '🇫🇰',
    code: 'FK',
    dialCode: '500',
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    id: 74,
    name: 'Faroe Islands',
    flag: '🇫🇴',
    code: 'FO',
    dialCode: '298',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 71,
    name: 'Fiji',
    flag: '🇫🇯',
    code: 'FJ',
    dialCode: '679',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 70,
    name: 'Finland',
    flag: '🇫🇮',
    code: 'FI',
    dialCode: '358',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 75,
    name: 'France',
    flag: '🇫🇷',
    code: 'FR',
    dialCode: '33',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 80,
    name: 'French Guiana',
    flag: '🇬🇫',
    code: 'GF',
    dialCode: '594',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 175,
    name: 'French Polynesia',
    flag: '🇵🇫',
    code: 'PF',
    dialCode: '689',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 216,
    name: 'French Southern Territories',
    flag: '🇹🇫',
    code: 'TF',
    dialCode: '262',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 76,
    name: 'Gabon',
    flag: '🇬🇦',
    code: 'GA',
    dialCode: '241',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 85,
    name: 'Gambia',
    flag: '🇬🇲',
    code: 'GM',
    dialCode: '220',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 79,
    name: 'Georgia',
    flag: '🇬🇪',
    code: 'GE',
    dialCode: '995',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 57,
    name: 'Germany',
    flag: '🇩🇪',
    code: 'DE',
    dialCode: '49',
    minLength: 9,
    maxLength: 13,
  ),
  Country(
    id: 82,
    name: 'Ghana',
    flag: '🇬🇭',
    code: 'GH',
    dialCode: '233',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 83,
    name: 'Gibraltar',
    flag: '🇬🇮',
    code: 'GI',
    dialCode: '350',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 89,
    name: 'Greece',
    flag: '🇬🇷',
    code: 'GR',
    dialCode: '30',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 84,
    name: 'Greenland',
    flag: '🇬🇱',
    code: 'GL',
    dialCode: '299',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 78,
    name: 'Grenada',
    flag: '🇬🇩',
    code: 'GD',
    dialCode: '1473',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 87,
    name: 'Guadeloupe',
    flag: '🇬🇵',
    code: 'GP',
    dialCode: '590',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 92,
    name: 'Guam',
    flag: '🇬🇺',
    code: 'GU',
    dialCode: '1671',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 91,
    name: 'Guatemala',
    flag: '🇬🇹',
    code: 'GT',
    dialCode: '502',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 81,
    name: 'Guernsey',
    flag: '🇬🇬',
    code: 'GG',
    dialCode: '44',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 86,
    name: 'Guinea',
    flag: '🇬🇳',
    code: 'GN',
    dialCode: '224',
    minLength: 8,
    maxLength: 9,
  ),
  Country(
    id: 93,
    name: 'Guinea-Bissau',
    flag: '🇬🇼',
    code: 'GW',
    dialCode: '245',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 94,
    name: 'Guyana',
    flag: '🇬🇾',
    code: 'GY',
    dialCode: '592',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 99,
    name: 'Haiti',
    flag: '🇭🇹',
    code: 'HT',
    dialCode: '509',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 96,
    name: 'Heard Island and Mcdonald Islands',
    flag: '🇭🇲',
    code: 'HM',
    dialCode: '672',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 236,
    name: 'Holy See (Vatican City State)',
    flag: '🇻🇦',
    code: 'VA',
    dialCode: '379',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 97,
    name: 'Honduras',
    flag: '🇭🇳',
    code: 'HN',
    dialCode: '504',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 95,
    name: 'Hong Kong',
    flag: '🇭🇰',
    code: 'HK',
    dialCode: '852',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 100,
    name: 'Hungary',
    flag: '🇭🇺',
    code: 'HU',
    dialCode: '36',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 109,
    name: 'Iceland',
    flag: '🇮🇸',
    code: 'IS',
    dialCode: '354',
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    id: 105,
    name: 'India',
    flag: '🇮🇳',
    code: 'IN',
    dialCode: '91',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 101,
    name: 'Indonesia',
    flag: '🇮🇩',
    code: 'ID',
    dialCode: '62',
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    id: 108,
    name: 'Iran, Islamic Republic of Persian Gulf',
    flag: '🇮🇷',
    code: 'IR',
    dialCode: '98',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 107,
    name: 'Iraq',
    flag: '🇮🇶',
    code: 'IQ',
    dialCode: '964',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 102,
    name: 'Ireland',
    flag: '🇮🇪',
    code: 'IE',
    dialCode: '353',
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    id: 104,
    name: 'Isle of Man',
    flag: '🇮🇲',
    code: 'IM',
    dialCode: '44',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 103,
    name: 'Israel',
    flag: '🇮🇱',
    code: 'IL',
    dialCode: '972',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 110,
    name: 'Italy',
    flag: '🇮🇹',
    code: 'IT',
    dialCode: '39',
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    id: 112,
    name: 'Jamaica',
    flag: '🇯🇲',
    code: 'JM',
    dialCode: '1876',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 114,
    name: 'Japan',
    flag: '🇯🇵',
    code: 'JP',
    dialCode: '81',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 111,
    name: 'Jersey',
    flag: '🇯🇪',
    code: 'JE',
    dialCode: '44',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 113,
    name: 'Jordan',
    flag: '🇯🇴',
    code: 'JO',
    dialCode: '962',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 125,
    name: 'Kazakhstan',
    flag: '🇰🇿',
    code: 'KZ',
    dialCode: '7',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 115,
    name: 'Kenya',
    flag: '🇰🇪',
    code: 'KE',
    dialCode: '254',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 118,
    name: 'Kiribati',
    flag: '🇰🇮',
    code: 'KI',
    dialCode: '686',
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    id: 121,
    name: "Korea, Democratic People's Republic of Korea",
    flag: '🇰🇵',
    code: 'KP',
    dialCode: '850',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 122,
    name: 'Korea, Republic of South Korea',
    flag: '🇰🇷',
    code: 'KR',
    dialCode: '82',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 123,
    name: 'Kuwait',
    flag: '🇰🇼',
    code: 'KW',
    dialCode: '965',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 116,
    name: 'Kyrgyzstan',
    flag: '🇰🇬',
    code: 'KG',
    dialCode: '996',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 126,
    name: 'Laos',
    flag: '🇱🇦',
    code: 'LA',
    dialCode: '856',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 135,
    name: 'Latvia',
    flag: '🇱🇻',
    code: 'LV',
    dialCode: '371',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 127,
    name: 'Lebanon',
    flag: '🇱🇧',
    code: 'LB',
    dialCode: '961',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 132,
    name: 'Lesotho',
    flag: '🇱🇸',
    code: 'LS',
    dialCode: '266',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 131,
    name: 'Liberia',
    flag: '🇱🇷',
    code: 'LR',
    dialCode: '231',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 136,
    name: 'Libyan Arab Jamahiriya',
    flag: '🇱🇾',
    code: 'LY',
    dialCode: '218',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 129,
    name: 'Liechtenstein',
    flag: '🇱🇮',
    code: 'LI',
    dialCode: '423',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 133,
    name: 'Lithuania',
    flag: '🇱🇹',
    code: 'LT',
    dialCode: '370',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 134,
    name: 'Luxembourg',
    flag: '🇱🇺',
    code: 'LU',
    dialCode: '352',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 148,
    name: 'Macao',
    flag: '🇲🇴',
    code: 'MO',
    dialCode: '853',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 144,
    name: 'Macedonia',
    flag: '🇲🇰',
    code: 'MK',
    dialCode: '389',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 142,
    name: 'Madagascar',
    flag: '🇲🇬',
    code: 'MG',
    dialCode: '261',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 156,
    name: 'Malawi',
    flag: '🇲🇼',
    code: 'MW',
    dialCode: '265',
    minLength: 7,
    maxLength: 9,
  ),
  Country(
    id: 158,
    name: 'Malaysia',
    flag: '🇲🇾',
    code: 'MY',
    dialCode: '60',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 155,
    name: 'Maldives',
    flag: '🇲🇻',
    code: 'MV',
    dialCode: '960',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 145,
    name: 'Mali',
    flag: '🇲🇱',
    code: 'ML',
    dialCode: '223',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 153,
    name: 'Malta',
    flag: '🇲🇹',
    code: 'MT',
    dialCode: '356',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 143,
    name: 'Marshall Islands',
    flag: '🇲🇭',
    code: 'MH',
    dialCode: '692',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 150,
    name: 'Martinique',
    flag: '🇲🇶',
    code: 'MQ',
    dialCode: '596',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 151,
    name: 'Mauritania',
    flag: '🇲🇷',
    code: 'MR',
    dialCode: '222',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 154,
    name: 'Mauritius',
    flag: '🇲🇺',
    code: 'MU',
    dialCode: '230',
    minLength: 7,
    maxLength: 8,
  ),
  Country(
    id: 246,
    name: 'Mayotte',
    flag: '🇾🇹',
    code: 'YT',
    dialCode: '262',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 157,
    name: 'Mexico',
    flag: '🇲🇽',
    code: 'MX',
    dialCode: '52',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 73,
    name: 'Micronesia, Federated States of Micronesia',
    flag: '🇫🇲',
    code: 'FM',
    dialCode: '691',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 139,
    name: 'Moldova',
    flag: '🇲🇩',
    code: 'MD',
    dialCode: '373',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 138,
    name: 'Monaco',
    flag: '🇲🇨',
    code: 'MC',
    dialCode: '377',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 147,
    name: 'Mongolia',
    flag: '🇲🇳',
    code: 'MN',
    dialCode: '976',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 140,
    name: 'Montenegro',
    flag: '🇲🇪',
    code: 'ME',
    dialCode: '382',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 152,
    name: 'Montserrat',
    flag: '🇲🇸',
    code: 'MS',
    dialCode: '1664',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 137,
    name: 'Morocco',
    flag: '🇲🇦',
    code: 'MA',
    dialCode: '212',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 159,
    name: 'Mozambique',
    flag: '🇲🇿',
    code: 'MZ',
    dialCode: '258',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 146,
    name: 'Myanmar',
    flag: '🇲🇲',
    code: 'MM',
    dialCode: '95',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 60,
    name: 'Namibia',
    flag: '🇳🇦',
    code: 'NA',
    dialCode: '264',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 169,
    name: 'Nauru',
    flag: '🇳🇷',
    code: 'NR',
    dialCode: '674',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 168,
    name: 'Nepal',
    flag: '🇳🇵',
    code: 'NP',
    dialCode: '977',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 166,
    name: 'Netherlands',
    flag: '🇳🇱',
    code: 'NL',
    dialCode: '31',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 161,
    name: 'New Caledonia',
    flag: '🇳🇨',
    code: 'NC',
    dialCode: '687',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 171,
    name: 'New Zealand',
    flag: '🇳🇿',
    code: 'NZ',
    dialCode: '64',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 165,
    name: 'Nicaragua',
    flag: '🇳🇮',
    code: 'NI',
    dialCode: '505',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 162,
    name: 'Niger',
    flag: '🇳🇪',
    code: 'NE',
    dialCode: '227',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 164,
    name: 'Nigeria',
    flag: '🇳🇬',
    code: 'NG',
    dialCode: '234',
    minLength: 10,
    maxLength: 11,
  ),
  Country(
    id: 170,
    name: 'Niue',
    flag: '🇳🇺',
    code: 'NU',
    dialCode: '683',
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    id: 163,
    name: 'Norfolk Island',
    flag: '🇳🇫',
    code: 'NF',
    dialCode: '672',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 149,
    name: 'Northern Mariana Islands',
    flag: '🇲🇵',
    code: 'MP',
    dialCode: '1670',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 167,
    name: 'Norway',
    flag: '🇳🇴',
    code: 'NO',
    dialCode: '47',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 172,
    name: 'Oman',
    flag: '🇴🇲',
    code: 'OM',
    dialCode: '968',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 178,
    name: 'Pakistan',
    flag: '🇵🇰',
    code: 'PK',
    dialCode: '92',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 185,
    name: 'Palau',
    flag: '🇵🇼',
    code: 'PW',
    dialCode: '680',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 183,
    name: 'Palestinian Territory, Occupied',
    flag: '🇵🇸',
    code: 'PS',
    dialCode: '970',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 173,
    name: 'Panama',
    flag: '🇵🇦',
    code: 'PA',
    dialCode: '507',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 176,
    name: 'Papua New Guinea',
    flag: '🇵🇬',
    code: 'PG',
    dialCode: '675',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 186,
    name: 'Paraguay',
    flag: '🇵🇾',
    code: 'PY',
    dialCode: '595',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 174,
    name: 'Peru',
    flag: '🇵🇪',
    code: 'PE',
    dialCode: '51',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 177,
    name: 'Philippines',
    flag: '🇵🇭',
    code: 'PH',
    dialCode: '63',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 181,
    name: 'Pitcairn',
    flag: '🇵🇳',
    code: 'PN',
    dialCode: '64',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 179,
    name: 'Poland',
    flag: '🇵🇱',
    code: 'PL',
    dialCode: '48',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 184,
    name: 'Portugal',
    flag: '🇵🇹',
    code: 'PT',
    dialCode: '351',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 182,
    name: 'Puerto Rico',
    flag: '🇵🇷',
    code: 'PR',
    dialCode: '1939',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 187,
    name: 'Qatar',
    flag: '🇶🇦',
    code: 'QA',
    dialCode: '974',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 189,
    name: 'Romania',
    flag: '🇷🇴',
    code: 'RO',
    dialCode: '40',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 191,
    name: 'Russia',
    flag: '🇷🇺',
    code: 'RU',
    dialCode: '7',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 192,
    name: 'Rwanda',
    flag: '🇷🇼',
    code: 'RW',
    dialCode: '250',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 188,
    name: 'Reunion',
    flag: '🇷🇪',
    code: 'RE',
    dialCode: '262',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 26,
    name: 'Saint Barthelemy',
    flag: '🇧🇱',
    code: 'BL',
    dialCode: '590',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 199,
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    flag: '🇸🇭',
    code: 'SH',
    dialCode: '290',
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    id: 120,
    name: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    code: 'KN',
    dialCode: '1869',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 128,
    name: 'Saint Lucia',
    flag: '🇱🇨',
    code: 'LC',
    dialCode: '1758',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 141,
    name: 'Saint Martin',
    flag: '🇲🇫',
    code: 'MF',
    dialCode: '590',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 180,
    name: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    code: 'PM',
    dialCode: '508',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 237,
    name: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    code: 'VC',
    dialCode: '1784',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 244,
    name: 'Samoa',
    flag: '🇼🇸',
    code: 'WS',
    dialCode: '685',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 204,
    name: 'San Marino',
    flag: '🇸🇲',
    code: 'SM',
    dialCode: '378',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 209,
    name: 'Sao Tome and Principe',
    flag: '🇸🇹',
    code: 'ST',
    dialCode: '239',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 193,
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    code: 'SA',
    dialCode: '966',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 205,
    name: 'Senegal',
    flag: '🇸🇳',
    code: 'SN',
    dialCode: '221',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 190,
    name: 'Serbia',
    flag: '🇷🇸',
    code: 'RS',
    dialCode: '381',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 195,
    name: 'Seychelles',
    flag: '🇸🇨',
    code: 'SC',
    dialCode: '248',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 203,
    name: 'Sierra Leone',
    flag: '🇸🇱',
    code: 'SL',
    dialCode: '232',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 198,
    name: 'Singapore',
    flag: '🇸🇬',
    code: 'SG',
    dialCode: '65',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 202,
    name: 'Slovakia',
    flag: '🇸🇰',
    code: 'SK',
    dialCode: '421',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 200,
    name: 'Slovenia',
    flag: '🇸🇮',
    code: 'SI',
    dialCode: '386',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 194,
    name: 'Solomon Islands',
    flag: '🇸🇧',
    code: 'SB',
    dialCode: '677',
    minLength: 5,
    maxLength: 5,
  ),
  Country(
    id: 206,
    name: 'Somalia',
    flag: '🇸🇴',
    code: 'SO',
    dialCode: '252',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 247,
    name: 'South Africa',
    flag: '🇿🇦',
    code: 'ZA',
    dialCode: '27',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 208,
    name: 'South Sudan',
    flag: '🇸🇸',
    code: 'SS',
    dialCode: '211',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 90,
    name: 'South Georgia and the South Sandwich Islands',
    flag: '🇬🇸',
    code: 'GS',
    dialCode: '500',
    minLength: 15,
    maxLength: 15,
  ),
  Country(
    id: 68,
    name: 'Spain',
    flag: '🇪🇸',
    code: 'ES',
    dialCode: '34',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 130,
    name: 'Sri Lanka',
    flag: '🇱🇰',
    code: 'LK',
    dialCode: '94',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 196,
    name: 'Sudan',
    flag: '🇸🇩',
    code: 'SD',
    dialCode: '249',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 207,
    name: 'Suriname',
    flag: '🇸🇷',
    code: 'SR',
    dialCode: '597',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 201,
    name: 'Svalbard and Jan Mayen',
    flag: '🇸🇯',
    code: 'SJ',
    dialCode: '47',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 213,
    name: 'Eswatini',
    flag: '🇸🇿',
    code: 'SZ',
    dialCode: '268',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 197,
    name: 'Sweden',
    flag: '🇸🇪',
    code: 'SE',
    dialCode: '46',
    minLength: 13,
    maxLength: 13,
  ),
  Country(
    id: 43,
    name: 'Switzerland',
    flag: '🇨🇭',
    code: 'CH',
    dialCode: '41',
    minLength: 12,
    maxLength: 12,
  ),
  Country(
    id: 212,
    name: 'Syrian Arab Republic',
    flag: '🇸🇾',
    code: 'SY',
    dialCode: '963',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 228,
    name: 'Taiwan',
    flag: '🇹🇼',
    code: 'TW',
    dialCode: '886',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 219,
    name: 'Tajikistan',
    flag: '🇹🇯',
    code: 'TJ',
    dialCode: '992',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 229,
    name: 'Tanzania, United Republic of Tanzania',
    flag: '🇹🇿',
    code: 'TZ',
    dialCode: '255',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 218,
    name: 'Thailand',
    flag: '🇹🇭',
    code: 'TH',
    dialCode: '66',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 221,
    name: 'Timor-Leste',
    flag: '🇹🇱',
    code: 'TL',
    dialCode: '670',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 217,
    name: 'Togo',
    flag: '🇹🇬',
    code: 'TG',
    dialCode: '228',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 220,
    name: 'Tokelau',
    flag: '🇹🇰',
    code: 'TK',
    dialCode: '690',
    minLength: 4,
    maxLength: 4,
  ),
  Country(
    id: 224,
    name: 'Tonga',
    flag: '🇹🇴',
    code: 'TO',
    dialCode: '676',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 226,
    name: 'Trinidad and Tobago',
    flag: '🇹🇹',
    code: 'TT',
    dialCode: '1868',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 223,
    name: 'Tunisia',
    flag: '🇹🇳',
    code: 'TN',
    dialCode: '216',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 225,
    name: 'Turkey',
    flag: '🇹🇷',
    code: 'TR',
    dialCode: '90',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 222,
    name: 'Turkmenistan',
    flag: '🇹🇲',
    code: 'TM',
    dialCode: '993',
    minLength: 8,
    maxLength: 8,
  ),
  Country(
    id: 214,
    name: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    code: 'TC',
    dialCode: '1649',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 227,
    name: 'Tuvalu',
    flag: '🇹🇻',
    code: 'TV',
    dialCode: '688',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 231,
    name: 'Uganda',
    flag: '🇺🇬',
    code: 'UG',
    dialCode: '256',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 230,
    name: 'Ukraine',
    flag: '🇺🇦',
    code: 'UA',
    dialCode: '380',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 2,
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    code: 'AE',
    dialCode: '971',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 77,
    name: 'United Kingdom',
    flag: '🇬🇧',
    code: 'GB',
    dialCode: '44',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 233,
    name: 'United States',
    flag: '🇺🇸',
    code: 'US',
    dialCode: '1',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 234,
    name: 'Uruguay',
    flag: '🇺🇾',
    code: 'UY',
    dialCode: '598',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 235,
    name: 'Uzbekistan',
    flag: '🇺🇿',
    code: 'UZ',
    dialCode: '998',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 242,
    name: 'Vanuatu',
    flag: '🇻🇺',
    code: 'VU',
    dialCode: '678',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 238,
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    flag: '🇻🇪',
    code: 'VE',
    dialCode: '58',
    minLength: 10,
    maxLength: 10,
  ),
  Country(
    id: 241,
    name: 'Vietnam',
    flag: '🇻🇳',
    code: 'VN',
    dialCode: '84',
    minLength: 11,
    maxLength: 11,
  ),
  Country(
    id: 239,
    name: 'Virgin Islands, British',
    flag: '🇻🇬',
    code: 'VG',
    dialCode: '1284',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 240,
    name: 'Virgin Islands, U.S.',
    flag: '🇻🇮',
    code: 'VI',
    dialCode: '1340',
    minLength: 7,
    maxLength: 7,
  ),
  Country(
    id: 243,
    name: 'Wallis and Futuna',
    flag: '🇼🇫',
    code: 'WF',
    dialCode: '681',
    minLength: 6,
    maxLength: 6,
  ),
  Country(
    id: 245,
    name: 'Yemen',
    flag: '🇾🇪',
    code: 'YE',
    dialCode: '967',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 248,
    name: 'Zambia',
    flag: '🇿🇲',
    code: 'ZM',
    dialCode: '260',
    minLength: 9,
    maxLength: 9,
  ),
  Country(
    id: 249,
    name: 'Zimbabwe',
    flag: '🇿🇼',
    code: 'ZW',
    dialCode: '263',
    minLength: 9,
    maxLength: 9,
  ),
];

class Country {
  final int id;
  final String name;
  final String flag;
  final String code;
  final String dialCode;
  final int minLength;
  final int maxLength;

  const Country({
    required this.id,
    required this.name,
    required this.flag,
    required this.code,
    required this.dialCode,
    required this.minLength,
    required this.maxLength,
  });

  @override
  String toString() {
    return 'Country(id: $id, name: $name, flag: $flag, code: $code, dialCode: $dialCode, minLength: $minLength, maxLength: $maxLength)';
  }
}
